color0 #23163c
color1 #fd4663
color2 #9167e4
color3 #c25cd6
color4 #cc66aa
color5 #b193ec
color6 #db96e9
color7 #f2f2f3
color8 #666170
color9 #fd4663
color10 #9167e4
color11 #c25cd6
color12 #cc66aa
color13 #b193ec
color14 #db96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a112d
background            #1a112d
foreground            #f2f2f3
selection_foreground  #b1afb6
selection_background  #23163c
active_border_color   #9167e4
inactive_border_color #23163c
url_color             #9167e4

active_tab_foreground   #191421
active_tab_background   #9167e4
inactive_tab_foreground #b1afb6
inactive_tab_background #23163c
cursor_trail_color      #b1afb6
